# Generated by Django 3.1 on 2020-08-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='suggest',
            field=models.URLField(default='None'),
        ),
    ]
