# Generated by Django 3.1 on 2020-09-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_suggest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='suggest',
            field=models.TextField(default='None', max_length=200),
        ),
    ]
