# Generated by Django 3.1 on 2020-08-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='link',
        ),
        migrations.AddField(
            model_name='courses',
            name='youtube_id',
            field=models.CharField(default='None', max_length=300),
        ),
    ]
