# Generated by Django 3.1 on 2020-08-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200831_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='youtube_id',
            field=models.CharField(default='', max_length=300),
        ),
    ]
