# Generated by Django 3.1 on 2020-08-31 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200831_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecomment',
            name='parent',
        ),
    ]
