# Generated by Django 3.1 on 2020-08-31 13:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('category', models.CharField(default='', max_length=255)),
                ('credit', models.CharField(max_length=100)),
            ],
        ),
    ]
