# Generated by Django 3.1 on 2020-08-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='SocialMedia',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
