# Generated by Django 3.1 on 2020-08-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='SocialMedia',
            field=models.URLField(default='None', max_length=250),
        ),
    ]
