# Generated by Django 3.1 on 2020-08-31 06:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200827_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('slug', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=255)),
                ('youtube_channel', models.CharField(max_length=100)),
                ('link', models.URLField(default='', max_length=300)),
            ],
        ),
    ]
