# Generated by Django 3.1 on 2020-08-31 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_coursecomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coursecomment',
        ),
        migrations.DeleteModel(
            name='courses',
        ),
    ]
